apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: otel-collector
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - name: otlp-grpc
      port: {{ .Values.service.ports.otlpGrpc }}
      targetPort: otlp-grpc
    - name: otlp-http
      port: {{ .Values.service.ports.otlpHttp }}
      targetPort: otlp-http
